repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: check-ast
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3.11
        args: ["--target-version", "py311"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
    -   id: ruff
        args: [
            "--fix",
            "--target-version", "py311",
            "--select", "D,E,F,B,I,N,UP,S,C4",
            "--ignore", "D203,D213",
            "--line-length", "88"
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            "types-requests",
            "numpy>=1.24.0",
        ]
        args: [
            "--python-version", "3.11",
            "--warn-return-any",
            "--warn-unused-configs",
            "--disallow-untyped-defs",
            "--disallow-incomplete-defs",
            "--check-untyped-defs",
            "--disallow-untyped-decorators",
            "--no-implicit-optional",
            "--warn-redundant-casts",
            "--warn-unused-ignores",
            "--warn-no-return",
            "--warn-unreachable",
            "--strict-equality"
        ]
