exclude: |
    (?x)(
        # Virtual environments
        ^\.venv/|
        ^\.env/|

        # GitHub files
        ^\.github/|

        # Build and distribution
        ^build/|
        ^dist/|
        ^\.eggs/|
        ^\.tox/|

        # Cache directories
        ^\.pytest_cache/|
        ^\.mypy_cache/|
        ^\.ruff_cache/|
        ^\.git/|

        # Project-specific directories
        ^tests/data/|
        ^docs/generated/|
        ^tests/wip/|
        ^wip/.*|                # All files in root wip directory
        ^.*/wip/.*|            # All files in any wip directory

        # Temporary and binary files
        \.pyc$|
        \.pyi$|
        \.ipynb$|

        # Minified files
        \.min\.js$|
        \.min\.css$|

        # Binary and generated files
        \.pb\.go$|
        \.so$|
        \.dylib$|
        \.dll$|

        # Specific files
        ^version\.py|
        ^tests/.*/(__init__)\.py|
        ^src/preservationeval/main/tables\.py$$
    )

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: check-json
          - id: debug-statements
          - id: check-ast
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-docstring-first
          - id: check-symlinks
          - id: detect-private-key
          - id: requirements-txt-fixer
          - id: no-commit-to-branch
            args: [--branch, main]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.11
      hooks:
          - id: ruff
            types_or: [python, pyi]
            args: ["--fix"] # Other configs in pyproject.toml
          - id: ruff-format
            types_or: [python, pyi]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.17.1
      hooks:
          - id: mypy
            types_or: [python, pyi]
            additional_dependencies:
                ["types-requests>=2.31.0", "numpy>=1.24.0", "types-setuptools"]
