"""Placeholder for auto-generated tables module.

This file will be overwritten during package installation with the actual
lookup tables for preservation calculations.

Note:
    Do not edit this file directly as changes will be lost during installation.
"""

from preservationeval.table_types import (
    EMCTable,
    MoldTable,
    PITable,
)

pi_table: PITable
mold_table: MoldTable
emc_table: EMCTable
