"""Placeholder for auto-generated tables module.

This file will be overwritten during package installation with the actual
lookup tables for preservation calculations.

Note:
    Do not edit this file directly as changes will be lost during installation.
"""

# This file is a placeholder and will be replaced during installation
raise NotImplementedError(
    "Tables module not generated. Please install the package to generate tables."
)
