name: Auto PR
on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Create PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ github.token }}
          title: 'Auto PR: ${{ github.ref_name }} from @${{ github.actor }}'
          body: |
            Automated pull request from ${{ github.actor }}
            Branch: ${{ github.ref_name }}

            Changes in this PR:
            ${{ github.event.head_commit.message }}
          branch: ${{ github.ref_name }}
          base: main
