name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11"]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '22'

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        echo "Current directory: $(pwd)"
        echo "Directory contents: $(ls -la)"
        echo "Python path: $PYTHONPATH"
        python -m pip install -e ".[test]" -v
        echo "Post-install contents:"
        ls -R src/preservationeval/
        python -m pip install pre-commit

    - name: Cache pre-commit hooks
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      run: |
        pre-commit run --all-files

    - name: Run tests
      run: |
        pytest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
