name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11"]

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '22'

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        echo "Current directory: $(pwd)"
        echo "Directory contents: $(ls -la)"
        echo "Python path: $PYTHONPATH"
        python -m pip install -e ".[test]" -v
        echo "Post-install contents:"
        ls -R src/preservationeval/
        python -m pip install pre-commit

    - name: Cache pre-commit hooks
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      env:
        SKIP: no-commit-to-branch
      run: |
        pre-commit run --all-files

    - name: Run tests
      run: |
        pytest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
