name: Create Release and Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # This pattern matches semantic versioning tags like v1.0.0

permissions:
  contents: write


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create GitHub Release
      uses: ghalactic/github-release-from-tag@v5

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        rm -f src/preservationeval/tables.py
        python -m build

    - name: Verify tables.py removal
      run: |
        ! tar -tvf dist/*.tar.gz | grep '/tables.py'

    - name: Verify package
      run: twine check dist/*

    - name: Create test environment
      run: python -m venv test_env

    - name: Test built package
      run: |
        source test_env/bin/activate
        python -c "import glob; print(glob.glob('dist/*.gz')[0]+'[test]')" | xargs pip install -v
        pytest -v

    - name: Publish to PyPI
      if: success()
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*.gz

    - name: Verify PyPI package
      if: success()
      run: |
        sleep 60  # Wait for PyPI to process the upload
        source test_env/bin/activate
        pip uninstall -y preservationeval
        pip install --no-cache-dir "preservationeval[test]"
        pytest -v
