name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Verify package
      run: twine check dist/*

    - name: Create test environment
      run: python -m venv test_env

    - name: Get package name
      run: echo "PACKAGE_NAME=$(python setup.py --name)" >> $GITHUB_ENV

    - name: Test built package
      run: |
        source test_env/bin/activate
        python -c "import glob; print(glob.glob('dist/*.whl')[0]+'[test]')" | xargs pip install
        pip install pytest  # Ensure pytest is installed
        pytest tests/ -v

    - name: Publish to PyPI
      if: success()
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*

    - name: Verify PyPI package
      if: success()
      run: |
        sleep 60  # Wait for PyPI to process the upload
        source test_env/bin/activate
        pip uninstall -y ${{ env.PACKAGE_NAME }}
        pip install --no-cache-dir "${{ env.PACKAGE_NAME }}[test]"
        pytest tests/ -v
